### PR TITLE
Fix svn on Windows

### LINKED ISSUE #166: Problem with svn URLs on Windows
### Summary of Issue:

A user on a Windows machine reported a problem accessing an svn repository from a Windows machine. It looks like the svn URL got a backslash where it should have had a slash. See https://github.com/ESCOMP/CTSM/issues/362#issuecomment-1091143264

### Expected behavior and actual behavior:

Should be able to download svn repositories on Windows. Currently this fails due to there being a backslash in the URL

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

See https://github.com/ESCOMP/CTSM/issues/362#issuecomment-1091143264

### Screen output or log file showing the error message and context:

See https://github.com/ESCOMP/CTSM/issues/362#issuecomment-1091143264

### PR DESCRIPTION
**Pull request by billsacks**
Fix svn URLs on Windows

User interface changes?: No

Fixes: #166 

Testing:
  test removed: none
  unit tests: pass
  system tests: pass
  manual testing: tested obtaining CESM release-cesm2.1.3 on my Mac

### CODE REVIEW

**Comment by billsacks** [comment]
I don't have a Windows machine to test on, but I can see how this code would cause problems on Windows before this change. @fischer-ncar do you have a Windows machine to test this on? If not, we could enlist someone (maybe Cheryl?) to test this on Windows, or just bring it in figuring that this at least is an improvement over the previous state.

**Comment by fischer-ncar** [comment]
Yes, I have several Windows machines.  I'll test, approve, then merge this PR.

**Comment by billsacks** [comment]
The user who reported this issue says that this fix solves the problem on Windows: https://github.com/ESCOMP/CTSM/issues/362#issuecomment-1092514684

**Comment by fischer-ncar** [comment]
Thanks for the update.  I could never get it to fail on my Windows machine.

**Review by fischer-ncar — APPROVED** [review]

**Pull request merged**
