### PR TITLE
Add support for git sparse checkout

### LINKED ISSUE #120: Support for Git sparse checkout
### Summary of Issue:   

Provide option to have git suppress some directories in the work tree.  E.g. our CTM app must include our entire GCM to obtain the advection core.  (Chemistry will be in a separate repo).   By using git "sparse checkout" capabilities, CTM users will not see most of the rest of the GCM - just the core directory.

In theory this could be avoided by adopting an even more fine-grained repository decomposition, but we are not prepared to go as far as would be required.  Virtually all changes would then span multiple repositories which is undesirable.

### Expected behavior and actual behavior:  

Config file would have an optional entry for each repo which specifies a "sparse" config file that would be used to exercise native git capabilities  to suppress directories.   This would be applied _after_ switching branches.

Example providing this option
```config
[GEOSgcm_GridComp]
required = True
repo_url = git@developer.nasa.gov:GEOSproto/GEOSgcm.git
local_path = ./src/Components/GEOSgcm_GridComp
branch = master
protocol = git
externals = Externals.cfg
sparse-checkout = my_sparse
```
Example sequence of extra commands that would be issued during the configuration:

```shell
git config core.sparsecheckout true
cp <sparse-checkout> $GITDIR/info/sparse-checkout
git read-tree -mu HEAD
```
It really is just a matter of tacking these 3 commands to the end of the git checkout sequence, which is why I'm confident this is an easy change without even looking at the python source.   I'm not wed to the particular name for the option.   "sparse-checkout" is the internal file name that Git  

### What is the changeset ID of the code, and the machine you are using:

N/A

### have you modified the code? If so, it must be committed and available for testing:

N/A

### Screen output or log file showing the error message and context:

N/A

### PR DESCRIPTION
**Pull request by gold2718**
Add support for git sparse checkout

Added a new, optional external property, sparse. sparse points to a file (relative to external repository local directory) with git sparse checkout patterns (e.g., directory names to include).
If the sparse keyword is included, enable sparse checkout for that repository and use git read-tree to perform the sparse checkout.

Added a new test for sparse checkout. The test is a repo with two externals which are both tag2 of the simple_ext repo with one of them configured for a sparse checkout. The test makes sure that both externals have the correct files.

Updated the documentation for the externals configuration file.

User interface changes?: Yes
New sparse keyword is optional with a blank default value which preserves current functionality.

Fixes: #120 

Testing:
  test removed: None
  unit tests: All passed
  system tests: All passed, including new test for sparse feature
  manual testing: Several manual tests of NASA test cases.

### CODE REVIEW

**Comment by jedwards4b** [comment]
@gold2718 please fix travis-ci tests

**Comment by tclune** [comment]
Note - I was hoping to take a stab at this over the weekend.   I'm still not sure how to do such a test in a way that does not involve creating and destroying repositories.   Presumably if I look at the existing tests, I'll either see how things are mocked or get more comfortable with a heavy weight test.

**Comment by gold2718** [comment]
@tclune,
There is a test for sparse checkout in the current PR. 
You can create and destroy repos in tests but you can also use the existing repos in test/repos.
For instance, for the new test I wrote, I added a file and tag to test/repos/simple-ext.git

**Review by billsacks — APPROVED** [review]
From a cursory look, looks good. (Sorry for the delay: I was on vacation last week.)

**Comment by tclune** [comment]
I had a quiet day and thought I would return to this issue.     I presume it has not been merged because of the decrease in coverage, and have investigated.   The few new lines of code that are not exercised are print statements activated when verbose is on.     I tried modifying the existing test to use `verbose_args` but that causes coverage to fail - presumably because I'm not properly handling  the extra stuff that then goes to STDOUT.

```script
======================================================================
FAIL: test_container_sparse (test_sys_checkout.TestSysCheckout)
Verify that 'full' container with simple subrepo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sys_checkout.py", line 1393, in test_container_sparse
    self._check_container_sparse_post_checkout(overall, tree)
  File "test_sys_checkout.py", line 913, in _check_container_sparse_post_checkout
    self._check_simple_tag_ok(tree)
  File "test_sys_checkout.py", line 676, in _check_simple_tag_ok
    self._check_generic_ok_clean_required(tree, name)
  File "test_sys_checkout.py", line 641, in _check_generic_ok_clean_required
    self.assertEqual(tree[name].sync_state, ExternalStatus.STATUS_OK)
AssertionError: u'e' != u' '
```

I tried to follow the examples from the other tests, but those are all using verbose_args after the initial clone.      What is the correct course of action here?

Note - I'm happy to add additional tests, but until I understand this issue, none will increase the code coverage to the best of my understanding.

**Comment by gold2718** [comment]
@tclune, I have been meaning to try and figure out what is wrong with our test coverage. I agree that something is messed up. For instance, when I _added_ the test for sparse checkout, the coverage went _down_. I think it is not worth further holding this PR for as I will not be able to look into this for at least another month.

**Pull request merged**
